### ISSUE TITLE
Recursive Types

### ISSUE THREAD

**Issue by Togrias** [ExpediaDotCom/graphql-kotlin#113]
Hello, it seems that recursive types (i.e. an object that has a field with the same type) not supported:

`class A {
  fun parent(): A? {
    // some implementation
  }
}`

Causes the following error:

Caused by: graphql.AssertException: type A not found in schema

**Comment by Togrias** [comment]
For the above error to occur, the object must reference itself. A schema with "A" referencing "B" and "B" referencing "A" works fine. But "A" referencing "A" breaks.

**Comment by smyrick** [comment]
How would you query the following? You would need and infinite expanding fragment.

```graphql
query {
  node {
    parent # This requires fields but it would go on infinitely 
  }
}

type Node {
  parent: Node
}

**Comment by smyrick** [comment]
Reading more here: https://github.com/facebook/graphql/issues/91

**Comment by Togrias** [comment]
The above data structure is useful for a tree diagram. Yes, queries are required to have a finite number of layers and the same fragment within itself is not allowed. I believe this is also enforced on most(?) client-side frameworks?

It is possible to do the above in graphql-java using GraphQLTypeReference(name).

**Comment by Togrias** [comment]
I'm not sure if it's a related issue, but when I tried to do a workaround (replacing the output with an interface supertype, such as Node), it throws an error: "interfaceType can't be null".

i.e. `class A(): Node {
 fun parent(): Node //Instead of A
 }`

**Comment by smyrick** [comment]
We now have an example query https://github.com/ExpediaDotCom/graphql-kotlin/blob/6f4b189b5786ce825848d75716b8429d7ddf0fd3/example/src/main/kotlin/com/expedia/graphql/sample/query/RecursiveQuery.kt
