### ISSUE TITLE
Cyclic schema definitions still don't work

### ISSUE THREAD

**Issue by Togrias** [ExpediaDotCom/graphql-kotlin#146]
Hi,

It seems the latest release broke cyclic schemas again. The following cyclic schema still doesn't work

````
graphql.AssertException: type Widget not found in schema
````
````
interface Node {@GraphQLID val id: String }
class User: Node {
@GraphQLID
override val id = ...
fun widget(@GraphQLContext context: Context): Widget = ...
}

class Widget: Node {
@GraphQLID
override val id = ...
fun user(@GraphQLContext context: Context): User = ...
}
````
I need to traverse User -> Widget -> User, and both are implementing Nodes.
It only works if I drop one of the cyclical references.

**Comment by smyrick** [comment]
@Togrias 

Can you provide a full unit test of a breaking schema?

You can place test it out in https://github.com/ExpediaDotCom/graphql-kotlin/tree/master/src/test/kotlin/com/expedia/graphql/integration

I made this test and it still passes

```kotlin
package com.expedia.graphql.integration

import com.expedia.graphql.TopLevelObject
import com.expedia.graphql.annotations.GraphQLContext
import com.expedia.graphql.annotations.GraphQLID
import com.expedia.graphql.testSchemaConfig
import com.expedia.graphql.toSchema
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class CyclicInterfaceTest {

    @Test
    fun cyclicInterface() {
        val queries = listOf(TopLevelObject(CyclicQuery()))
        val schema = toSchema(queries = queries, config = testSchemaConfig)
        assertEquals(1, schema.queryType.fieldDefinitions.size)
        val field = schema.queryType.fieldDefinitions.first()
        assertEquals("getWidget", field.name)
    }
}

class CyclicQuery {
    fun getWidget() = Widget()
}

interface CyclidNode {
    @GraphQLID
    val id: String
}

class User : CyclidNode {
    @GraphQLID
    override val id = "User"

    fun widget(@GraphQLContext context: String) = Widget()
}

class Widget : CyclidNode {
    @GraphQLID
    override val id = "Widget"

    fun user(@GraphQLContext context: String) = User()
}
```

**Comment by smyrick** [comment]
Or if you can not write a teat can you post the config and hooks you are using as well as you query class

**Comment by smyrick** [comment]
@Togrias We have unit test here that validate the recursive types: https://github.com/ExpediaDotCom/graphql-kotlin/tree/master/src/test/kotlin/com/expedia/graphql/integration

Can you validate that you are installing the latest version `0.0.33`. We changed the `groupId` in a previous release

```xml
<dependency>
  <groupId>com.expedia</groupId>
  <artifactId>graphql-kotlin</artifactId>
  <version>0.0.33</version>
</dependency>
```

**Comment by smyrick** [comment]
We can not reproduce this error. I am going to close.

If you are still having issues can you please provide the following and re-open the issue.

* Version information
* All kotlin code used for in schema
* Kotlin code used to call `toSchema` with configuration details
* A stack trace of the error

**Comment by smyrick** [comment]
@Togrias We fixed a bug that we had with `GraphQLTypeReference`s in our latest release. Can you test version `0.2.1` to see if you are still having issues with your graph.

If you are having a problem, you can post here with the data classes, query classes, and configuration and we can reopen the issue
