### ISSUE TITLE
Support subscriptions

### ISSUE THREAD

**Issue by smyrick** [ExpediaDotCom/graphql-kotlin#155]
GraphQL Java can support subscriptions: https://www.graphql-java.com/documentation/v11/subscriptions/

We just need to come up with a good way to represent the different type in the schema.

This may be able to be done without a breaking change. Can we just add a `@GraphQLSubscription`?

**Comment by smyrick** [comment]
FYI I have a WIP branch here: https://github.com/smyrick/graphql-kotlin/tree/subscribtions

I think we should update the example first to use the webflux as a demo, this can be done without supporting subscriptions but add them after will be much easier and help split up all the example changes I need to do to show how to use a publisher

**Comment by shahabio** [comment]
Whats the status for this? :roll_eyes:

**Comment by smyrick** [comment]
@shahabio I had started working on the update but had trouble getting the example app working with spring websockets. If you want to pick up from my branch you can pull from here: https://github.com/smyrick/graphql-kotlin/tree/subscribtions

**Comment by smyrick** [comment]
@camuthig When I run a subscription query through the playground and I put a breakpoint at the top of `SubscriptionHandler.handle()` I can see the value for `session.handshakeInfo.headers["Sec-WebSocket-Protocol"]` is `graphql-ws` so that is still being sent

**Comment by camuthig** [comment]
@smyrick I added the same breakpoint and agree that the header is there. However, when I use the dev console on Chromium to look at the response, I don't see it coming back on the response. 

The headers using graphql-spring-boot-autoconfigure look something like
```
Connection: upgrade
Date: Tue, 23 Apr 2019 08:55:26 GMT
Sec-WebSocket-Accept: <token>
Sec-WebSocket-Extensions: permessage-deflate;client_max_window_bits=15
Sec-WebSocket-Protocol: graphql-ws
Upgrade: websocket
```
But with your branch I'm seeing

```
connection: upgrade
sec-websocket-accept: <token>
upgrade: websocket
```

**Comment by smyrick** [comment]
With my latest branch I have successfully connected using the following Websocket client:

https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo

Is there an issue with GraphQL Playground and Spring Webflux Websockets? Specifically the `graphql-ws` protocol? https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/24

![Screen Shot 2019-05-03 at 5 15 17 PM](https://user-images.githubusercontent.com/2446877/57171226-38c70f80-6dc7-11e9-9e51-9625eaf528dc.png)

**Comment by hinterdupfinger** [comment]
putting

```
override fun getSubProtocols(): List<String> {
    return listOf("graphql-ws")
}
```

in `SubscriptionHandler(private val graphQL: GraphQL) : WebSocketHandler`

should fix the the protocol issue as `org.springframework.web.reactive.socket.server.support.HandshakeWebSocketService` is checking for supported protocols in the handler
