### ISSUE TITLE
Mutation - wrap group of functions by special type

### ISSUE THREAD

**Issue by TomLevvv** [ExpediaDotCom/graphql-kotlin#170]
Hi, 

I am trying to use this library,  but I cannot find an option to group a list of functions by specific type, for example:
My schema should be as the following:

```graphql
type Mutation {
    car: CarMutation
    person: PersonMutation
}

type CarMutation {
    createCar(input: CreateCarInput!): CreateCarResult!
    updateCar(input: UpdateCarInput): UpdateCarResult!
}

type PersonMutation {
    createPerson(input: CreatePersonInput!): CreatePersonResult!
    updatePerson(input: UpdatePersonInput): UpdatePersonResult!
}
```

But , the schema is generated like the following:
```graphql
type Mutation {
    createCar(input: CreateCarInput!): CreateCarResult!
    updateCar(input: UpdateCarInput): UpdateCarResult!
    createPerson(input: CreatePersonInput!): CreatePersonResult!
    updatePerson(input: UpdatePersonInput): UpdatePersonResult!
}
```
my data classes:
```kotlin
class CarMutation {
   fun createCar(input: CreateCarInput): CompletableFuture<CreateCarResult>? {
        return null
    }
  fun updateCar(input: UpdateCarInput): CompletableFuture<UpdateCarResult>? {
        return null
    }
  
} 

class PersonMutation {
   fun createPersonr(input: CreatePersonInput): CompletableFuture<CreatePersonResult>? {
        return null
    }
  
} 
```

main code:
```kotlin
@Service
class GraphQLMutationSchema(mutationTypes: MutationTypes) {

    val config = SchemaGeneratorConfig(listOf("example"), hooks = CustomSchemaGeneratorHooks)
    val queries = listOf(TopLevelObject(FakeQuery()))
    val mutations = listOf(TopLevelObject(carMutation), TopLevelObject(personMutation))

    fun generateSchema(): GraphQLSchema {
        return toSchema(queries, mutations, config)
    }

```

When I use a wrapper class to build the schema, no objects will be generated, because the library suppose all functions are declared in the first topLevel Object!!!
for example:
```
@Component
data class MutationTypes(val carMutation: CarMutation, val persopnMutation: PersonMutation)

 val mutations = listOf(TopLevelObject(mutationTypes))
```
when I build it with the wrapper class(MutationTypes) - no mutation function are generated!!!

the result:
type Mutation {
}

Great day
Tom Lev

**Comment by gscheibel** [comment]
Hello,

All the functions exposed directly by either queries or mutations are considered as `TopLevel` leading to what you see.

If you want to group mutations or queries, you have to return a type exposing function as well.
I've created a PR to add an example: https://github.com/ExpediaDotCom/graphql-kotlin/pull/171

In this case we leverage spring injection capabilities and it's not mandatory.
However it can important to pay attention to the scope used as a component scope (ei: singleton) can have some undesired side effects.

**Comment by TomLevvv** [comment]
Hi ,

That's exactly what I was looking for!!

Thanks!
Tom Lev

**Comment by smyrick** [comment]
So I through together a quick branch to try this out without the spring beans.

Would we want to make it easier for develeoper to access the `DataFetchingEnvironment`? If they have it as an argument for their function we could just hide it in the schema and pass it down so they can access levels all the way up.


```kotlin
fun nested(@GraphQLEnvironment environment: DataFetchingEnvironment, value: Int) = ContextualResponse(
        value,
        "parent value is ${environment.executionStepInfo.parent.arguments["value"]?.toString().orEmpty()}"
    )
```

![screen shot 2019-02-21 at 10 31 03 am](https://user-images.githubusercontent.com/2446877/53192645-d631e600-35c3-11e9-92aa-2bf4b419865b.png)

**Comment by smyrick** [comment]
I have added another way to get the parent arguments here: https://github.com/ExpediaDotCom/graphql-kotlin/pull/173
