### ISSUE TITLE
Recursive queries produce invalid schema introspection

### ISSUE THREAD

**Issue by smyrick** [ExpediaDotCom/graphql-kotlin#191]
### Library Version
0.2.7

### Describe the bug
There are `GraphQLTypeReference`s in the schema when a recursive query like [NodeGraphTest](https://github.com/ExpediaDotCom/graphql-kotlin/blob/6a9fcef7821908f3bf81ce4dac8abe33fd53ba78/src/test/kotlin/com/expedia/graphql/test/integration/NodeGraphTest.kt#L12) is used.

### To Reproduce
On the integration test [NodeGraphTest](https://github.com/ExpediaDotCom/graphql-kotlin/blob/6a9fcef7821908f3bf81ce4dac8abe33fd53ba78/src/test/kotlin/com/expedia/graphql/test/integration/NodeGraphTest.kt#L12), we actually have a failing schema. If you inspect the schema after build, you will notice that the type of `Node.parent` is `GraphQLTypeReference`. This should never happen as all schemas should have the full objects.

You can add the following assert to now make a failing test

```kotlin
assertFalse((schema.typeMap["Node"] as? GraphQLObjectType)?.getFieldDefinition("parent")?.type is GraphQLTypeReference)
```

### Expected behavior
There are no `GraphQLTypeReference` in the code. This is *fixed* if I use `graphql-java` `2019-03-07T04-34-55-809a980`

**Comment by smyrick** [comment]
https://spectrum.chat/graphql-java/general/next-release~54137901-d83a-4e8f-bad5-60842eabf279

**Comment by kaqqao** [comment]
For what it's worth, I think the issue can be worked around by creating a new `TypeReference` each time.
