### ISSUE TITLE
graphql-kotlin VS graphql-spqr

### ISSUE THREAD

**Issue by elenigen** [ExpediaDotCom/graphql-kotlin#196]
In [our project](https://github.expedia.biz/LPS/cs-attribute-content-service), we are using Kotlin with the [graphql-spqr](https://github.com/leangen/graphql-spqr) and I was wondering if you have ever compared the two libs, I would be curious to know the difference in terms of features.

Thanks!

**Comment by dkuc84** [comment]
I haven't looked in depth at `graphql-spqr` but I believe the biggest difference is in the way the schemas are generated -  `graphql-spqr` relies on explicit annotations and manual registration of the operations to build a schema whereas `graphql-kotlin` relies on Kotlin reflections to generate the schema directly from the code. While `graphql-kotlin` also ships with some [annotations](https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Annotations) they are optional and only used to enhance the schema with additional information that cannot be directly derived from Kotlin reflections.

Take a look at our [example project](https://github.com/ExpediaDotCom/graphql-kotlin/tree/master/example) to see how it could be integrated with Spring Boot.

**Comment by smyrick** [comment]
We are taking a "resolver first" approach and taking advantage of the reflection Kotlin has. You could potentially convert an existing Kotlin Spring Boot REST API code base into GraphQL without changing the logic or models with our library. I would advise against that though as REST models don't always translate to the best GraphQL schema.


I'm going to mark as closed/answered but please ask any other questions you might have as this will be searchable by others in the future!
