### ISSUE TITLE
Support kotlin.collections.Set

### ISSUE THREAD

**Issue by smyrick** [ExpediaDotCom/graphql-kotlin#201]
**Is your feature request related to a problem? Please describe.**
Right now the current support collections we can convert to a GraphQL list (`List`, `Array`) to do provide a uniqueness guarantee like `Set`

**Describe the solution you'd like**
We would like to use a [`Set<T>`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-set/index.html) as a unique collection of values instead of a `List<T>` or `Array<T>`

**Describe alternatives you've considered**
We could use `List` in the schema code but then we would have to manually perform some operation to remove duplicates in the list

**Additional context**
This is the error that is thrown when `Set` is used in the schema

```
Cannot convert kotlin.collections.Set<kotlin.String> since it is outside the supported packages [com.expedia]
```

**Comment by smyrick** [comment]
Probably a better way rather than just adding `Set` to the list of things we can check is to find someway to support all `Collections`

https://github.com/ExpediaDotCom/graphql-kotlin/blob/0e6bc8aaa82a5805939313baa2d9285941d17577/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt#L50

**Comment by tapaderster** [comment]
@smyrick do you want to support all `kotlin.Collections`?

**Comment by tapaderster** [comment]
> Probably a better way rather than just adding `Set` to the list of things we can check is to find someway to support all `Collections`
> 
> [graphql-kotlin/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt](https://github.com/ExpediaDotCom/graphql-kotlin/blob/0e6bc8aaa82a5805939313baa2d9285941d17577/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt#L52)
> 
> Line 52 in [0e6bc8a](/ExpediaDotCom/graphql-kotlin/commit/0e6bc8aaa82a5805939313baa2d9285941d17577)
> 
>  kClass.isListType() -> generator.listType(type, inputType)

@smyrick do you want to support all kotlin.Collections?

**Comment by tapaderster** [comment]
> Probably a better way rather than just adding `Set` to the list of things we can check is to find someway to support all `Collections`
> 
> [graphql-kotlin/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt](https://github.com/ExpediaDotCom/graphql-kotlin/blob/0e6bc8aaa82a5805939313baa2d9285941d17577/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt#L52)
> 
> Line 52 in [0e6bc8a](/ExpediaDotCom/graphql-kotlin/commit/0e6bc8aaa82a5805939313baa2d9285941d17577)
> 
>  kClass.isListType() -> generator.listType(type, inputType)

**Comment by smyrick** [comment]
@tapaderster The team brought up a good point that while `Set`s could be used from a server perspective that information is not part of the GraphQL spec so clients could pass in a list of items as input but if the server used a `Set` as the input then it would remove those items. The developer may want to do this but I feel like this would be an implementation detail and shouldn't be part of the schema serialization/deserialization.

My point being GraphQL really only supports lists, so we should as well. Do everyone agree?

**Comment by smyrick** [comment]
@ExpediaDotCom/graphql-kotlin Feedback anyone?

**Comment by dkuc84** [comment]
Since you cannot represent a set in GraphQL spec and there a builtins in the Kotlin lib to easily convert to/from set I'd not put any custom logic to schema generation to handle it.

**Comment by smyrick** [comment]
See updated discussion: https://github.com/ExpediaGroup/graphql-kotlin/discussions/1110

You can add `Set` support with custom hooks
