### ISSUE TITLE
kClassExtensions only check declared functions and properties

### ISSUE THREAD

**Issue by StarF666** [ExpediaDotCom/graphql-kotlin#204]
**Library Version**
0.2.9

**Describe the bug**
Extension functions getValidProperties and getValidFunctions in kClassExtension.kt only check declared members on KClass thus ommiting inherited properties and functions. This leads to validation error "object type 'SomeType' does not implement interface 'SomeInterface' because field 'SomeField' is missing". when using inheritance with abstract classes.

**To Reproduce**
My model:

```
interface SomeInterface {
  var someField: String?
}

abstract class SomeAbstractClass : SomeInterface {
   override var someField: String? = null
   var justAnotherField: String?
}

class SomeClass : SomeAbstractClass {
   override var justAnotherField: String? = null
}

```

**Expected behavior**
Interface generation should work with inherited fields, shouldn't it? kClassExtensions could use this.memberProperties/this.memberFunctions instead of this.declaredMemberProperties and this.declaredMemberFunctions.

**Comment by StarF666** [comment]
I tried and changed the code in kClassExtensions and it basically works. Would it make sense to rewrite the generator to generate GraphQL interfaces from abstract class inheritance? Or am I overlooking something?

**Comment by smyrick** [comment]
Thank you for reporting! I have pushed a PR as linked above solving the problem

**Comment by smyrick** [comment]
Released in https://github.com/ExpediaDotCom/graphql-kotlin/releases/tag/0.2.11
