### ISSUE TITLE
Example to configure use of mono, flux

### ISSUE THREAD

**Issue by vetm73** [ExpediaDotCom/graphql-kotlin#212]
I would like to use a spring reactive mongo repository with your framework. On https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Asynchronous-Models there is a sentence about doing this in SchemaGeneratorHooks.willResolveMonad but I have no clue how to do this. Could you help me a little bit where to start?

**Comment by smyrick** [comment]
Hello,

We have an example of how the hooks can be configured in a unit test. https://github.com/ExpediaDotCom/graphql-kotlin/blob/2b88d2d1793f3d0cdfcd8280483debe26d277ae2/src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorAsyncTests.kt#L19

I will update that wiki page though to provide more context.


You can check if the type is Mono or Flux in your own hook or you can convert to get the wrapped value. Does that answer your question?

**Comment by smyrick** [comment]
Updated the wiki: https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Asynchronous-Models

**Comment by vetm73** [comment]
This is perfect!

Thanks,
Mike
