### ISSUE TITLE
Query with input type

### ISSUE THREAD

**Issue by ddtxra** [ExpediaDotCom/graphql-kotlin#219]
Dear all,
Very nice library, bravo :)
I have a little question, I would like to generate a Graphql schema that is compatible with Prisma API (for queries only)...

Prisma defines its query arguments with an Input "criteria", that could be similar to this:
```kotlin
@Component
class AnimalQueries : Query {
    fun findAnimal(): Animal = Animal(1, "cat")
    fun findAnimals(where: AnimalCriteria) : List<Animal> = if("c".equals(criteria.type_contains)) .... // return cats 
}

data class AnimalCriteria(val type_contains: String?, val id_gte: Int?)
data class Animal(val id: Int,val type: String)
```
So one can write the following GraphQL query: 
```graphql
query {
  findAnimals(where: { type_contains: "c" }) {
    id
  }
}
```
My question is, what is your suggestion to generate the AnimalCriteria automatically? 

Ideally I would like to do something with annotations:
```kotlin
data class Animal(
@GraphQLCriterias({"gte", "eq", "in"})
val id: Int,
@GraphQLCriterias({"contains", "in"})
val type: String)

```

that would generate the following AnimalCriteria in the GraphQL schema "like Prisma"
https://www.prisma.io/docs/understand-prisma/prisma-vs-traditional-orms/prisma-vs-typeorm-k9fh/#other-filter-criteria

```graphql
input AnimalCriteriaInput {
  id_gte: Int
  id_lt: Int
  id_in: [Int]
  type_contains: String
  type_in: [String]
  OR: [AnimalCriteriaInput]
  AND: [AnimalCriteriaInput]
}
```
The main problem, is that one still need to use the AnimalCriteria in the code to implement the service taking into consideration the given criterias. 

```kotlin
fun findAnimals(where: AnimalCriteria) : List<Animal> = listOf(Animal(1, "dog"))
```
Do you have any suggestion on how to achieve this?

**Comment by dkuc84** [comment]
It sounds like your problem lies with automatic generation of the input `criteria` objects. If you were to generate those classes (maybe using something like https://github.com/square/kotlinpoet) then you could use resulting objects to build your schemas, i.e. `graphql-kotlin` generates the schemas based on the source code but it does not generate the source code.

**Comment by ddtxra** [comment]
Exactly! Thanks very much for your response and the reference!
