### ISSUE TITLE
Is it possible to set custom scalars for specific class properties of the same type?

### ISSUE THREAD

**Issue by pzavtoni** [ExpediaDotCom/graphql-kotlin#226]
Let's say we have this class as an example:
`data class Salary(
    val employer: Employer? = null,
    val amount: Int? = null,
    val month: Int? = null,
)`

When defining .graphql files for this type it is also possible to use Scalars for _month_ and _amount_.  In my case there is a Scalar used for _amount_ that validates that value is a positive one and for _month_ there is a Scalar that allows only values from 1 to 12.

By setting scalars in this way we can see in the schema the exact type used for this fields and also the description for each scalars.

In `CustomSchemaGeneratorHooks` we can define scalars only by type and I can't see any solution by using it for my purpose.

Is there any other solution for this?
If there is not any solution at the moment would it be possible to implement such a feature?

**Comment by smyrick** [comment]
Yes it is! We have an example of doing this same validation by using a `URL` type from Java which is converted to a GraphQL `String`.  https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Scalars#custom-scalars

So here you could create a custom `data class Month(val value: Int)` and have the validation in the constructor or in the coercing code

**Comment by dkuc84** [comment]
One thing to keep in mind though that if you do create custom scalars all your clients will also need to know how to properly serialize/deserialize those objects. 

Another approach is to add some validations on the server that will return validation error to the user.

**Comment by pzavtoni** [comment]
> So here you could create a custom `data class Month(val value: Int)` and have the validation in the constructor or in the coercing code

@smyrick thanks for your reply, I took this possibility in account but this will mess up some logic is already implemented...

I am just curious if this could be done without any additional classes for such custom scalars

**Comment by dkuc84** [comment]
Custom scalars need to be defined in their own classes/types - without it how would you distinguish between a regular `Int` and "restricted" `Int` value for your custom scalar? 

You could always do some validations on the server manually and return `GraphQLError` if input is invalid. Another alternative is to use [GraphQL Directives](https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Schema-Directives) to customize the behavior.

**Comment by pzavtoni** [comment]
@dkuc84 I am making use of validations already and it works, thanks.

I was thinking of an implementation like it's done with @GraphQLID annotation.

**Comment by dkuc84** [comment]
`@GraphQLID` converts the field to a GraphQL ID scalar type which is a built-in type. It has a special meaning (see the [docs](https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Scalars#id)) but it doesn't perform any validation of the fields. 

Even if you were to create a custom annotation that would convert your `Int` input to a custom scalar it would still be exposed in your GraphQL schema as a custom scalar type.
