### ISSUE TITLE
Apollo Federation Support

### ISSUE THREAD

**Issue by de55** [ExpediaDotCom/graphql-kotlin#238]
**Is your feature request related to a problem? Please describe.**
Support for generating schema as federated service. Federated services can be used by an apollo gateway to stitch together schemas from multiple graphql endpoints.

**Describe the solution you'd like**
Support generation of features in federation spec: https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

**Describe alternatives you've considered**
N/A

**Additional context**
I use this project at work and want the benefits of a federated service. I am finishing up a different project now, but can start working on this in a few weeks. I wanted to check to see if you thought these additions would be an appropriate fit for this project.

**Comment by dkuc84** [comment]
Thanks for creating the issue. This is indeed on our backlog but unfortunately it is currently blocked by https://github.com/ExpediaDotCom/graphql-kotlin/issues/216

**Comment by de55** [comment]
Looks like 216 is closed now. You mentioned it is on the backlog, is this something that is expected to be implemented soon?

**Comment by de55** [comment]
@dkuc84 Looks like 216 is closed now. You mentioned it is on the backlog, is this something that is expected to be implemented soon?

**Comment by dkuc84** [comment]
I briefly looked into it (my WIP branch -> https://github.com/dkuc84/graphql-kotlin/tree/federation) to see how much work it would take to support federation and unfortunately it requires larger effort. Currently it looks like I won't be able to work on it anytime soon so feel free to pick it up.

Apollo released sample [federation-jvm](https://github.com/apollographql/federation-jvm) project that is an extension to `graphql-java`. Logic there applies transformation to an existing schema and relies on users providing manual resolver logic for the federated types. It could technically work but what is currently missing is the "glueing" part to generate federated query objects using `graphql-kotlin` - adding support for directives is pretty simple but what is problematic is that those federated queries are NOT part of query graph (i.e. they are not reachable from root queries). 

I'm thinking we would probably need to extend `SchemaGenerator` from `graphql-kotlin-schema-generator` that would take as an input list of those federated query objects (what would be problematic though is how those objects get instantiated).

**Comment by formanojhr** [comment]
Does this enhancement help with Grapql-java to support apollo federation support?

**Comment by smyrick** [comment]
@formanojhr Our implementation is directed at being used with the schema generation of GraphQL Kotlin Schema Generator

If you want a simple addition to GraphQL Java you can use https://github.com/apollographql/federation-jvm/blob/master/README.md
