### ISSUE TITLE
SDL support

### ISSUE THREAD

**Issue by Globegitter** [ExpediaDotCom/graphql-kotlin#240]
The example here shows how one can define the schema as classes and then convert that to sdl. graphql-java also supports defining the schema in sql and then wire that together, see: https://www.graphql-java.com/documentation/v13/schema/

Is that also supported by graphql-kotlin?

**Comment by dkuc84** [comment]
`graphql-kotlin` generates you a GraphQL schema. You can easily print it out as SDL and we provide an example how to do it in the sample app

https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/example/src/main/kotlin/com/expedia/graphql/sample/RoutesConfiguration.kt#L45

**Comment by dkuc84** [comment]
I think I misunderstood your question -> is your question whether `graphql-kotlin` can load schema from SDL? Answer to this is no, we don't support that as we are following resolver first approach and believe that your code should be the single source of truth for defining your schema.

**Comment by Globegitter** [comment]
Yeah exactly that is the questions - loading a schema from SDL. I actually think having a programming language agnostic schema as the source of truth makes the most sense. You might be having your graphql service implemented in a different language and want to switch to kotlin, or vice-versa you want to switch away from kotlin. But also the use-case that we have is that we want our schema to be away from the code so it can be looked at and maintained by multiple parties in the company, including frontend developers and QA. Trying to get them to co-maintain our kotlin schema will be impossible. That is a nice thing about protobuf - you have a language independent schema that can much easier be co-maintained.

Also as note, we are not using graphql internally yet but are considering it and that would be a must-have requirement.

Are there any other disadvantages you see of supporting the SDL I am not considering?

**Comment by dkuc84** [comment]
Both `schema-first` and `resolver-first` approaches have their shortcomings (see [this nice writeup](https://www.prisma.io/blog/the-problems-of-schema-first-graphql-development-x1mn4cb0tyl3)). In my opinion `schema-first` approach is more problematic as you have two sources of truth -> schema and code. This translates into more work as even after you define your schema you still have to implement it/map it to correct resolvers and types. As a result whenever you change your schema file you also need to update corresponding code (only exception would be documentation). 

Personally I am also not sure how often you would be migrating services from one language to another (at least I would hope you don't do it very often). Even if such scenario does happens then you can always generate SDL from your service and use it as a basis for reimplementing it in another language.

**Comment by smyrick** [comment]
@Globegitter I think you may be confused on where `graphql-kotlin` fits in with `graphql-java`. You can create a GraphQL server in Kotlin code using `graphql-java` today without any extra libs. The one downside to creating a server is that you need to either define the schema in an SDL file and load it as you described above or use the verbose schema building methods https://www.graphql-java.com/documentation/v13/schema/

Either way you will need resolvers which implement the same types as your schema which leads to duplication and two sources of truth.

i.e.

> Most GraphQL libraries require developers to maintain two sources of truth for their GraphQL API: the schema and the corresponding code (data fetchers or resolvers, and types). Given the similarities between Kotlin and GraphQL, such as the ability to define nullable/non-nullable types, a schema can be generated from Kotlin code without any separate schema specification. graphql-kotlin builds upon graphql-java to allow code-only, or resolver-first, GraphQL services to be built.

So the purpose of this library is to not use SDL files for schema definition and instead generate the schema from your resolver code. As @dkuc84 already mentioned though, both approaches have their downsides. If you would like to use a SDL file you can just use `graphql-java` directly.

**Comment by Globegitter** [comment]
@dkuc84 @smyrick Thanks for clearing things up and giving some more background - but wouldn't the best of both worlds then be code generation? So my SDL file is the source of truth and that then generates some Resolver interface to be implemented. So yes, the schema would still be the source of truth but with the correct tooling it should not lead to more work because all you have to do is add the missing resolvers and the IDE/compiler will complain if anything was missed.

But either way will also investigate graphql-java further - thanks again.

**Comment by rharriso** [comment]
> ...  both worlds then be code generation? So my SDL file is the source of truth and that then generates some Resolver interface to be implemented.

I think this makes sense in abstract, as you would be programming against the abstraction, rather than generating it. However, practically I find that generating the schema from source works better for me. There are fewer steps for getting a new Queries/Mutations/Types into the API. Also, there is no need to ensure that the entire graph is implemented, this is guarenteed by the code first approach.
