### ISSUE TITLE
Is there any way to extract the generated graphql schema?

### ISSUE THREAD

**Issue by gabsima-nexapp** [ExpediaDotCom/graphql-kotlin#243]
We implemented a serverless solution for our product with this library to handle the graphql layer. The only problem is that we have to generate the schema for every requests since we don't have a running instance to generate the schema on boot.

As our schema grow, so does the time to generate the schema. We were wondering if there is any way we could extract the generated schema so we could put it in a redis cache for our subsequent requests to fetch from.

**Comment by rharriso** [comment]
You can use a `SchemaPrinter` to print the generated `graphql-java` Schema to a string. Is that what you are looking for?

```kotlin
val graphQLSchema = toSchema(config, queries, mutations)
System.out.println(SchemaPrinter().print(graphQLSchema))
```

**Comment by gabsima-nexapp** [comment]
Thanks! That's what i was looking for to extract the schema. However, is there any way i can create a `GraphQLSchema` from this string?

**Comment by rharriso** [comment]
You could with `graphql-java`, but you'd have to implement/bind the revolvers separately.

You might find this thread helpful: https://github.com/ExpediaDotCom/graphql-kotlin/issues/240#issuecomment-503743254

**Comment by smyrick** [comment]
@gabsima-nexapp The output of `toSchema` is a `graphql.schema.GraphQLSchema` object from `graphql-java`. You need this for run time but you can also run this code as part of your build step and generate an SDL file as @rharriso mentioned, then load that into your server instead of generating the schema. 

This means you can cache the SDL file in Redis, S3, or any other place you need. 

----

Separate question, is the schema generation really taking that long? We "cache" the types as we generate them so we don't have to walk complex objects every time, and for our services, most of the start up time is for other things like Spring initialization.

**Comment by gabsima-nexapp** [comment]
I've noticed there was indeed some cache optimization for subsequent call on an api server. The problem is that i don't think this caching can be used in a serverless environment as the memory can be wiped for subsequent call. I might be wrong, but i've run some tests and here are my findings

On a server generating the schema for each calls:
- The first call took 1.7seconds to generate the schema
- Any subsequent calls took less than 100ms

However, i think we lose all these caching optimisation on a serverless environment because we might always hit the first call. This is why we are thinking of a solution to generate the schema at build time and loading it when booting the lambda.

Although, we also tried different solutions to optimize our network lag. Creating the schema in a companion object might share the instance on subsequent lambda calls if it is still warm. We also set up an health check to ensure our lambda is always warm. I think these solutions might be enough for our current needs. I'm still running tests right now.

Thanks for the documentation @smyrick this looks exactly like what we might need!

**Comment by rharriso** [comment]
@gabsima-nexapp

Let me know what you come up with, I’m also assessing  this library in a Lamba setup.

**Comment by gabsima-nexapp** [comment]
Creating the schema in a companion object combined with a scheduled CloudWatch event to keep the lambda alive did the trick! Our calls are all under 100ms now. I think creating the schema in a companion object keeps the schema in memory. As long as the lambda is alive, it does not need to generate them again.

**Comment by rharriso** [comment]
@gabsima-nexapp thats the approach I'm looking at as well. Is the keepalive request against the schema or against a rest api route?

**Comment by gabsima-nexapp** [comment]
For now it's against the lambda directly, a direct invocation. @rharriso
