### ISSUE TITLE
Deprecated directive is missing from the schema

### ISSUE THREAD

**Issue by dkuc84** [ExpediaDotCom/graphql-kotlin#246]
**Library Version**
latest snapshot

**Describe the bug**
`@deprecated` directive is no longer applied to the schema

![Screen Shot 2019-07-01 at 8 33 38 AM](https://user-images.githubusercontent.com/9501705/60440910-771c5780-9bdb-11e9-8980-e305cf893dcc.png)

**To Reproduce**
Run example app and check generated schema - it contains 5 directives (custom `@lowercase`, `@stringEval` and `@cakeOnly` as well as `@skip` and `@include` built-in ones). 

**Expected behavior**
Schema should contain `@deprecated` directive as some fields (e.g. `simpleDeprecatedQuery` are deprecated)

**Comment by rharriso** [comment]
It looks like this bug goes back at least to version 0.3.0. I used the following diff

```diff
diff --git a/src/test/kotlin/com/expedia/graphql/directives/DirectiveTests.kt b/src/test/kotlin/com/expedia/graphql/directives/DirectiveTests.kt
index ca97e01..b9c5ef9 100644
--- a/src/test/kotlin/com/expedia/graphql/directives/DirectiveTests.kt
+++ b/src/test/kotlin/com/expedia/graphql/directives/DirectiveTests.kt
@@ -36,6 +36,7 @@ class DirectiveTests {
 
         assertTrue(query.isDeprecated)
         assertEquals("this query is also deprecated, replace with shinyNewQuery", query.deprecationReason)
+        assertTrue(query.directives.stream().anyMatch { it.name == "deprecated" })
     }
 
     @Test
@@ -45,6 +46,7 @@ class DirectiveTests {
         val query = topLevelQuery.getFieldDefinition("deprecatedQuery")
         assertTrue(query.isDeprecated)
         assertEquals("this query is deprecated", query.deprecationReason)
+        assertTrue(query.directives.stream().anyMatch { it.name == "deprecated" })
     }
```
I also set breakpoints on those tests, and saw no directives on `schema.queryType`

**Comment by rharriso** [comment]
It looks like the `DirectiveBuilder` only supports `GraphqlDirectiveAnnotation` instances. 

```kotlin
    internal fun directives(element: KAnnotatedElement): List<GraphQLDirective> =
        element.annotations
            .mapNotNull { it.getDirectiveInfo() }
            .map(this::getDirective)

private fun Annotation.getDirectiveInfo(): DirectiveInfo? = this.annotationClass.annotations
    .filterIsInstance(GraphQLDirectiveAnnotation::class.java)
    .map { DirectiveInfo(this, it) }
    .firstOrNull()

private data class DirectiveInfo(val directive: Annotation, val directiveAnnotation: GraphQLDirectiveAnnotation) {
    val effectiveName: String = when {
        directiveAnnotation.name.isNotEmpty() -> directiveAnnotation.name
        else -> directive.annotationClass.getSimpleName().normalizeDirectiveName()
    }
}
```

The `Annotations.getDirectiveInfo` function returns null for `@Deprecated` as that annotation doesn't extend `GraphqlDirectiveAnnotation`

**Comment by rharriso** [comment]
Should `@Deprecated` be treated as a special case? Or should `DirectiveInfo` handle more Annotations that don't extend `GraphQLDirectiveAnnotation`

**Comment by smyrick** [comment]
@rharriso `Deprecated` shouldn't need to be handled by our code as it is internal to `graphql-java` and set when doing the field/type building: https://github.com/ExpediaDotCom/graphql-kotlin/blob/1d00b99fc174f322ac60e7863b3f8c80346a075d/src/main/kotlin/com/expedia/graphql/generator/types/PropertyBuilder.kt#L25

@dkuc84 Is this in fact an issue with our library or the schema printer in `graphql-java`?

**Comment by dkuc84** [comment]
It appears that there are multiple potential issues
* `playground` related issues [339](https://github.com/prisma/graphql-playground/issues/339) and [816](https://github.com/prisma/graphql-playground/issues/816) - currently `playground` doesn't handle deprecated well (as compared to `graphiql`)
* `graphql-java` related issue [1434](https://github.com/graphql-java/graphql-java/issues/1434) - currently `graphql-java` filters out "common" directives (`skip`, `include`, `defer` and `deprecated`) from printing in SDL. 
* `graphql-java` also only adds the deprecated directive to the schema when manually loading it from the file (e.g. here -> https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaGenerator.java#L265)
* `graphql-java` adds `@depreacted` directives directly to instrumentation results (e.g. here https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/introspection/IntrospectionResultToSchema.java#L237)

**Comment by dkuc84** [comment]
`@deprecated` directive is pretty special in a sense that it is just informational as there is no associated `RuntimeWiring` behind it that would customize it behavior. I was thinking something along those lines -> https://github.com/ExpediaDotCom/graphql-kotlin/pull/247
