### ISSUE TITLE
Support renaming of GraphQL fields

### ISSUE THREAD

**Issue by dkuc84** [ExpediaDotCom/graphql-kotlin#248]
`@GraphQLName` can be used to rename GraphQL types (i.e. classes). It is a fairly generic annotation so wondering whether we should extend its usage to also allow renaming of the GraphQL fields, etc, example schema

```kotlin
class RenamedQuery {
  @GraphQLName("renamed")  // currently unsupported
  fun original(id: Int) = OriginalType(id)
}

@GraphQLName("RenamedType")
class OriginalType(
  @GraphQLName("renamedProperty") //currently unsupported
  val originalProperty: Int
)
```

Could generate following SDL
```graphql
type Query {
  renamed(id: Int!): RenamedType!
}

type RenamedType {
  renamedProperty: Int!
}
```

**Comment by juliansxw** [comment]
Love this one! Currently, query name is the same as function name. It would be nice if we could override it

**Comment by Swissbite** [comment]
@dkuc84  What is the benefit of such a possibility?

That's just my opinion, but such code always leads to unnecessarily complex stuff. I would prefer to rename the function rather than just fake the name with an annotation.

I'm a fan of clean and clear code with no surprises.

**Comment by dkuc84** [comment]
@Swissbite in general I'd assume renaming of any of the fields would be rather uncommon. It is a fairly generic annotation but only applicable on a class (i.e. `GraphQLObjectType`). Since we are already providing functionality to rename the types (driven by use case from [here](https://github.com/ExpediaDotCom/graphql-kotlin/issues/210)) I think it would make sense to make it consistent and applicable on other GraphQLTypes as well.

As for actual use case for renaming functions/fields I don't have a concrete example but I'm thinking that it could be potentially useful in large federated schemas - if you have dozens of microservices building your graph you might want to provide some common naming patterns among them or need to rename some of the queries to avoid conflicts.

**Comment by smyrick** [comment]
@Swissbite I would tend to agree that we will not use this in our schemas much either but as @dkuc84 mentioned, we already support the annotation so this is just extending it's capabilities for those that do want to use it.
