### ISSUE TITLE
Support GraphQL ID scalar as function arguments and return types

### ISSUE THREAD

**Issue by dkuc84** [ExpediaDotCom/graphql-kotlin#249]
**Library Version**
Latest

**Describe the bug**
`@GraphQLID` annotation is ignored on the query arguments and it is currently not possible to return an ID type.

**To Reproduce**
Example schema

```kotlin
class QueryWithId {
  fun queryById(@GraphQLID id: String) = TypeWithId(id, "junit")
  fun queryForId() = ???
}

class TypeWithId(
  @GraphQLID
  val id: String,
  val name: String
)
```

**Expected behavior**
We should be able to generate schema with following SDL

```graphql
type Query {
  queryById(id: ID!): TypeWithId!  // currently it is just a String
  queryForId: ID                              // currently there is no way to define this
}

type TypeWithId {
  id: ID!
  name: String!
}
```

We could potentially introduce some custom wrapper and corresponding coercing logic
```kotlin
@GraphQLName("ID")
data class GraphQLID<T>(val id: T)
```

**Comment by smyrick** [comment]
This would make it easier to contain the ID type checks

**Comment by smyrick** [comment]
I can reproduce this with the following test in FunctionBuilderTest

https://github.com/ExpediaDotCom/graphql-kotlin/blob/a13e883608bd598926f36b89e4af013cbe93efde/graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt

```kotlin
@Test
    fun `ID argument type is valid`() {
        val kFunction = Happy::id
        val result = builder.function(fn = kFunction, parentName = "Query")

        assertEquals(expected = 1, actual = result.arguments.size)
        assertEquals(expected = "ID", actual = (result.arguments.firstOrNull()?.type as? GraphQLNonNull)?.wrappedType?.name)
        assertEquals("String", (result.type as? GraphQLNonNull)?.wrappedType?.name)
    }
```
