### ISSUE TITLE
update library structure

### ISSUE THREAD

**Issue by dkuc84** [ExpediaDotCom/graphql-kotlin#254]
`graphql-kotlin` is currently a single module project but it also contains standalone example project under root directory, i.e.  our current library structure is

```
graphql-kotlin [lib project]
  |- example [example app project]
```

Even though example APP project is under `graphql-kotlin` directory it is not a child project of `graphql-kotlin`.

Maybe we should restructure the project as

```
graphql-kotlin [root]
|- graphql-kotlin-schema [move + rename existing lib]
|- graphql-kotlin-spring-example [rename existing example]
```

This would allow us to create more specialized packages in the future, e.g.
* `graphql-kotlin-federation` - schema extension for supporting GraphQL federation spec
* `graphql-kotlin-engine` - native kotlin query runtime (i.e. drop dependency on `graphql-java`)
* `graphql-kotlin-spring-server` - boilerplate code for setting up Spring apps (i.e. our example app)
* `graphql-kotlin-ktor-server`
* `graphql-kotlin-client` - Kotlin native GraphQL client
* ... and potentially some others

**Comment by smyrick** [comment]
This sounds good to me. Especially renaming the library. That means we would be published as a different artifact. So I would vote to go explicit `graphql-kotlin-schema-generator` because we can have a separate package if with wanted to publish the schema as its own package.
