### ISSUE TITLE
How to query fields asynchronously?

### ISSUE THREAD

**Issue by heirofsigma** [ExpediaDotCom/graphql-kotlin#277]
I am building one service by using Kotlin, Ktor and Graphql-Kotlin library. The goal is to send queries to one Service API and get back data. I have three fields in Graphql query: Source, Target and Corridor. 

I want to run fields queries asynchronously, so I made a QueryHandler file to implement that. To check whether that handler works, I used Jaeger to trace my field queries.  The problem is QueryHandler did not work, which means my field queries run sequentially not asynchronously.

Some of my core code:
Main function:
`val queries: List<TopLevelObject> = listOf(
    TopLevelObject(
        Source
    ),
    TopLevelObject(
        Target
    ),
    TopLevelObject(
        Corridor
    )
)`
...
 `route("/graphql") {`
     `post {`
         `val request: GraphQLRequest = call.receive<GraphQLRequest>()`
         `val query: String = request.query`      
         `val result: ExecutionResult = QueryHandler(newGraphQL((schema)).build(), request).executeAsync()`
         `call.respond(result.toSpecification())`
     `}
 }    `    

QueryHandler:
![Screen Shot 2019-07-22 at 4 51 15 PM](https://user-images.githubusercontent.com/34078666/61672588-0b408280-aca1-11e9-8ecb-b4aa6b6504be.png)

Field Query function:
`fun Source(arguments) {`
    `    val span = tracer.buildSpan("getSource").childOf(parentSpan).start()`
    `    val result = accessor.get()`
    `    span.finish`
    `    return result`
`}`

The result I got by using Jaeger Tracing:
![span](https://user-images.githubusercontent.com/34078666/61672159-6d988380-ac9f-11e9-8b0e-aa10f3764c65.png)

**Comment by dkuc84** [comment]
@heirofsigma can you share working snippet? My guess (and only a guess) is that most likely your functions are not written as suspendable coroutines ([FunctionDataFetcher.kt](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/execution/FunctionDataFetcher.kt#L51)).

You can verify the behavior by modifying the [example app](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/Application.kt#L87) to include `TracingInstrumentation`
```kotlin
@Bean
fun graphQL(
    schema: GraphQLSchema,
    dataFetcherExceptionHandler: DataFetcherExceptionHandler
): GraphQL = GraphQL.newGraphQL(schema)
    .queryExecutionStrategy(AsyncExecutionStrategy(dataFetcherExceptionHandler))
    .mutationExecutionStrategy(AsyncSerialExecutionStrategy(dataFetcherExceptionHandler))
    .subscriptionExecutionStrategy(SubscriptionExecutionStrategy(dataFetcherExceptionHandler))
    .instrumentation(TracingInstrumentation())  // add Apollo tracing instrumentation from graphql-java
    .build()
```

You can then verify the asynchronous behavior by using the following query (`slowFunction` returns reversed msg delayed by 1s -> [link](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/query/CoroutineQuery.kt#L25)) :
```graphql
query multiple {
  first: slowFunction(msg: "first")
  second: slowFunction(msg: "second")
  third: slowFunction(msg: "third")
}
```

I'm getting the following response
```json
{
  "data": {
    "first": "tsrif",
    "second": "dnoces",
    "third": "driht"
  },
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2019-07-23T00:06:22.956Z",
      "endTime": "2019-07-23T00:06:23.961Z",
      "duration": 1004327414,
      ...
```

**Comment by heirofsigma** [comment]
@dkuc84 
You are right, I actually do not use coroutine in my field query functions. Do you mean that I should refactor my query functions with suspendable coroutines and try it again? I may refactor my code and post them latter.

**Comment by dkuc84** [comment]
With the current version of library only coroutine calls are executed async. Regular function calls are just invoked as is as they could potentially return results wrapped in some monads (e.g. CompletableFuture or RxJava/Reactor reactive types). 

You could configure your GraphQL schema with a [KotlinDataFetcherFactoryProvider](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/execution/KotlinDataFetcherFactoryProvider.kt) to provide custom data fetcher that has different behavior or alternatively configure different execution strategy (e.g. deprecated [ExecutorServiceExecutionStrategy](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java). I'd recommend though to migrate towards the use of coroutines.

**Comment by heirofsigma** [comment]
The question has been resolved,  I created one `TracingInstrumentation` like @dkuc84 said, and used it like:
`val result = newGraphQL((schema))
                            .queryExecutionStrategy(AsyncExecutionStrategy(SimpleDataFetcherExceptionHandler()))
                            .instrumentation(TracingGraphQLInstrumentation(GlobalTracer.get()))
                            .build()
                            .execute(query)`

Then I refactored my query functions(resolvers) with coroutine and async:

    
    coroutineScope {
        val deferredResult = async {
            // get your data here
        }
        result = deferredResult.await()
    }
    return result

The final result is like this:
![Screen Shot 2019-07-26 at 4 32 13 PM](https://user-images.githubusercontent.com/34078666/61986277-004c6180-afc3-11e9-89e9-7f17efedc4c0.png)
