### ISSUE TITLE
How to return one Custom return type

### ISSUE THREAD

**Issue by heirofsigma** [ExpediaDotCom/graphql-kotlin#283]
I have several custom data classes called `CorridorInformation`,  ` ProductOfferingInformation` and `PaymentMethodInformation`, they are like:

```kotlin
data class CorridorInformation(
    var sourceCountry: String = "",
    var targetCountry: String = "",
    var availabilityStatus: String = "",
    var crossStackRank: List<String> = listOf(),
    var productStackRank: List<String> = listOf(),
    var productOfferings: List<ProductOfferingInformation> = listOf()
)

data class ProductOfferingInformation(
    var product_name: String = "",
    var source_country: String = "",
    var target_country: String = "",
    var source_currency: String = "",
    var target_currency: String = "",
    var availability_status: String = "",
    var support_payment_methods: List<PaymentMethodInformation> = listOf()
)

data class PaymentMethodInformation(
    var paymentType: String = "",
    var availabilityStatus: String = ""
)
```

At last each field is in scalar type`String`. One field query called `corridor` will return a CorridorInformation type. My goal is to print CorridorInformation type in a clean format like
this:
![moreDetailedoNe](https://user-images.githubusercontent.com/34078666/62083495-e9e51680-b20b-11e9-9a73-90ec429c3174.png)

The question is do I have a way to define `CorridorInformation` a `scalar` type, so that I do not have to type those query commands but just with one single command `corridor(sourceCountry:"USA", targetCountry: "PER")`, then get the result format like I posted?

I find https://github.com/ExpediaDotCom/graphql-kotlin/issues/83 is useful, but all the examples were just printing simple object like `url` or `UUID`. My case here is one nested format, If I used  `SchemaGeneratorHooks`, can I get the final result format like what I posted?

**Comment by smyrick** [comment]
@heirofsigma You can only represent custom scalars with values of existing scalars so no this is not possible. 

If you want clients to just pass in a simple query

```graphql
query SimpleQuery {
  corridor(sourceCountry:"USA", targetCountry: "PER")
}
```

but then the response is a JSON object that is not a string, this goes against the type system and spec of GraphQL. If you need all this info for a very specific reason you could encode the large object as a JSON string and then the query field `corridor` could just return a string which is JSON, but then you are losing all the other benefits of GraphQL.

You may want to first look at why you might want to use GraphQL in the first place for your APIs.
* https://www.trygql.com/
* https://www.prisma.io/blog/top-5-reasons-to-use-graphql-b60cfa683511

**Comment by heirofsigma** [comment]
@smyrick Honestly that is a good news to me, I will stick to my old way to get this `corridor`. But my colleague will do more work on other end point instead.
