### ISSUE TITLE
How to pass HTTP header to graphql resolvers?

### ISSUE THREAD

**Issue by heirofsigma** [ExpediaDotCom/graphql-kotlin#286]
I am using Ktor server with graphql-kotlin. I have three field resolvers. The whole process is I send query(with a header) from GraphiQL app, then my Ktor server get the query, at last one graphql builder is created to execute queries.  

This piece of code is like:

     post {
         val request = call.receive<GraphQLRequest>()
         val query = request.query
         val header = call.request.headers.get("MyHeader")         
         val result = newGraphQL((schema))            
    .queryExecutionStrategy(AsyncExecutionStrategy(SimpleDataFetcherExceptionHandler()))
         .instrumentation(TracingGraphQLInstrumentation(GlobalTracer.get()))
         .build()
         .execute(query)
         call.respond(result.toSpecification())
    }

The goal is I should pass header sent by GraphiQL to all my field resolvers, and my resolvers should extract the header and pass them to further downstream services. I could get the header sent by GraphiQL by using `val header = call.request.headers.get("MyHeader")`. 

The question is how to pass this header to field resolvers, and how do these field resolvers extract this header, then wrap with field queries and send it to downstream services?  

I found one similar question here: https://stackoverflow.com/questions/49776031/how-to-pass-request-headers-through-to-graphql-resolvers
Seems like we could pass a `context` to field resolvers, and extract the header from this context. Does this library support this operation?

**Comment by dkuc84** [comment]
Yes you should create GraphQL context with the required data and add it to the execution input (see https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/GraphQLRequest.kt#L17). 

Our default data fetcher will automatically pass it to your target functions (see https://github.com/ExpediaDotCom/graphql-kotlin/wiki/@GraphQLContext) - you can either annotate the argument with [@GraphQLContext](https://github.com/ExpediaDotCom/graphql-kotlin/wiki/@GraphQLContext) or you can read it from the environment directly. You can see an example of how it works in our spring app -> https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/query/ContextualQuery.kt

**Comment by heirofsigma** [comment]
@dkuc84 Hi, Thank you for the advice, this a good point, I am following your method. But it seems like @GraphQLContext have conflicts with Google Guice @Inject annotation, and this @Inject will be executed first, then leads to one Guice injection unbounded problem. 

class GetCorridorResolver {
    private var accessor: Accessor
    private var bugsnag: BugsnagSetting? = null
    private var myGraphqlContext: MyGraphqlContext

    @Inject
    constructor(accessor: Accessor,
                bugsnag: BugsnagSetting?,
                @GraphQLContext myGraphqlContext: MyGraphqlContext
    ) {
        this.accessor = accessor
        this.bugsnag = bugsnag
        this.myGraphqlContext = myGraphqlContext
    }

I have already wrapped headers in my GraphQL ExecutionInput like:

`val result = newGraphQL((schema))                       .queryExecutionStrategy(AsyncExecutionStrategy(SimpleDataFetcherExceptionHandler()))
       .instrumentation(TracingGraphQLInstrumentation(GlobalTracer.get()))
       .build()
       .execute(GraphQLRequest(query, request.operationName, request.variables)
       .toExecutionInput(MyGraphqlContext(call.request.headers)))`


You said I could read context from my environment directly, how could I read my graphqlContext (which has already been wrapped in ExecutionInput)in resolver directly?

**Comment by dkuc84** [comment]
GraphQL context holds contextual information about current query execution so it should not be part of the constructor and should be passed to the resolvers, i.e. `@GraphQLContext myGraphqlContext: MyGraphqlContext` should be specified as a target function argument.

**Comment by heirofsigma** [comment]
@dkuc84 Thank you, your solution works perfectly.
