### ISSUE TITLE
Support generate schema from Generics

### ISSUE THREAD

**Issue by huangciyin** [ExpediaDotCom/graphql-kotlin#292]
Support generate schema from generics, avoid verbose define Connection/Edge class for every type.
example:
```
type Edge<T> {
  cursor: String
  node: T
}

class Connection<T>{
  edges: List<Edge<T>>
  pageInfo: PageInfo
}

class BookQuery: QueryResolver {
   fun find(value: Int): Connection<Book>
}
```
should generate schema like this:
```
schema {
  query: Query
}

type Query {
    find(value: Int!): ConnectionWithBook!
}
```
`ConnectionWithBook` is an object generated from `Connection<T>`.

**Comment by dkuc84** [comment]
`graphql-kotlin-schema-generator` uses reflections to generate corresponding schema. We are severely limited with what we can do with generics due to the type erasure and I don't think this can be reliably supported.

Feel free to explore the potential implementations though!

**Comment by smyrick** [comment]
@huangciyin Here is the relevant discussion in the GraphQL spec. Currently generics are not supported https://github.com/graphql/graphql-spec/issues/190

So for your feature we couldn't have full generics but instead you want to generate a type for every combination of the wrapping type and it's generic. ie a type of `Connection<Book>` generates two types `ConnectionBook` `EdgeBook`

With some of the points brought up in that thread I am not sure if we want to implement this in the library. Would this behavior be better described with a Union?

What do you think @ExpediaDotCom/graphql-kotlin?

**Comment by tiranuom** [comment]
@dkuc84 You guys have done a great job on creating the `graphql-kotlin` library. Many thanks for that.

We can improve this library with the generic support if we switch from reflection to a kotlin compiler plugin, which will eventually enable the boilerplate generation on behalf of the developer.

**Comment by smyrick** [comment]
@tiranuom That could be an option but we would also lose some of the benefits of having our library being callable from the client code, and as we stated, generics are not part of the GraphQL spec yet so we don't want to stray to being an experimental library.

That being said, I would love to see an example of how this might work if you want to fork our library. I personally have not worked at integrating at the compiler level so I would love to see an example of some of the benefits!

**Comment by dkuc84** [comment]
Since generics are currently not supported by the GraphQL spec we shouldn't add any custom logic to handle it at the moment. We can reopen this issue once the spec is updated.
