### ISSUE TITLE
feature: federation example

### ISSUE THREAD

**Issue by dkuc84** [ExpediaDotCom/graphql-kotlin#300]
**Is your feature request related to a problem? Please describe.**
We added ability to generate federated GraphQL schema with https://github.com/ExpediaDotCom/graphql-kotlin/pull/280. We should create example apps that showcase how to federated schemas would work.

**Describe the solution you'd like**
Create two example GraphQL services (one base and one that extends the functionality) and a federated GraphQL gateway

Potential structure

```
graphql-kotlin
|- federation-example
  |- federated-example-base-app
  |- federated-example-extend-app
  |- federated-gateway
```

**Comment by smyrick** [comment]
Resolved by https://github.com/ExpediaDotCom/graphql-kotlin/pull/315
