### ISSUE TITLE
Incorrect Federation SDL

### ISSUE THREAD

**Issue by meza** [ExpediaDotCom/graphql-kotlin#308]
**Library Version**
1.0.0-RC4

**Describe the bug**
The SDL queried by `query GetServiceDefinition { _service { sdl } }` contains
```
schema {\n  query: Query\n}\n\n#Space separated list of primary keys needed to access federated object\ndirective @key(fields: _FieldSet!) on OBJECT | INTERFACE\n\n
``` 
these headers + other directive information whereas the SDL should only contain the pure schema with no directives, and schema keyword.

This breaks a nodeJS ApolloGateway federation implementation.

**To Reproduce**
Use a federation server with an actual apollo federation nodejs gateway.

**Expected behavior**
The SDL string should be clean

**Comment by dkuc84** [comment]
I believe this is already resolved with https://github.com/ExpediaDotCom/graphql-kotlin/pull/302 and https://github.com/ExpediaDotCom/graphql-kotlin/pull/304

We will be releasing RC6 soon.

**Comment by meza** [comment]
Correct! I've just locally built RC5-SNAPSHOT and it's fixed. Thanks!
