### ISSUE TITLE
Recursive relationships fail in Graphql Federation

### ISSUE THREAD

**Issue by de55** [ExpediaDotCom/graphql-kotlin#310]
**Library Version**
1.0.0-RC4

**Describe the bug**
Recursive relationship causes a java.lang.ClassCastException due to graphql.schema.GraphQLTypeUtil.unwrapAll

**To Reproduce**
The following schema causes an error: "Caused by: java.lang.ClassCastException: class graphql.schema.GraphQLTypeReference cannot be cast to class graphql.schema.GraphQLUnmodifiedType (graphql.schema.GraphQLTypeReference and graphql.schema.GraphQLUnmodifiedType are in unnamed module of loader 'app')"

```kotlin
@Component
class ObjectAQuery: Query {
    fun objectA() = ObjectA()
}

class ObjectA(){
    val description = "ObjectA"
    fun nextObject() =ObjectA()
}
```
The following schema would also fail:
```kotlin
@Component
class ObjectAQuery: Query {
    fun objectA() = ObjectA()
}

class ObjectA(){
    val description = "ObjectA"
    fun objectB() =ObjectB()
}

@Component
class ObjectBQuery: Query {
    fun objectB() = ObjectB()
}

class ObjectB(){
    val description = "ObjectB"
    fun objectA() = ObjectA()
}
```

**Expected behavior**
Should generate the following schema:
```graphql
type _Service {
  sdl: String!
}

type ObjectA {
  description: String!
  nextObject: ObjectA!
}
```

**Comment by smyrick** [comment]
This appears to be a valid issue on our end, fixed by above ☝️
