### ISSUE TITLE
Any way to intercept thrown errors?

### ISSUE THREAD

**Issue by gabsima-nexapp** [ExpediaDotCom/graphql-kotlin#314]
I would like to be able to intercept thrown exceptions to log them with sentry before they become GraphQLErrors. Is there any way to do that?

**Comment by smyrick** [comment]
If an exception is thrown in one of your functions (data fetchers) you can catch it with traditional Kotlin `catch` and throw again to return a GraphQL errors. This will allow you to catch specific errors and log them in a certain manner


```kotlin

@GraphQLDescription("Get user data, may fail")
fun user(id: String): User {
    try {
        return getUserData(id)
    }
    catch (exception: Exception) {
        logToSentry(exception)
        throw exception
    }
}
```

**Comment by gabsima-nexapp** [comment]
Thanks! That's exactly what i was looking for! 🎺

**Comment by dkuc84** [comment]
@gabsima-nexapp while the above certainly will work, you can also configure custom global exception handler per your execution strategy (see [config](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/Application.kt#L87) and [exception handler](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/exceptions/CustomDataFetcherExceptionHandler.kt))
