### ISSUE TITLE
Support optional inputs?

### ISSUE THREAD

**Issue by Togrias** [ExpediaDotCom/graphql-kotlin#50]
The official graphql specs supports optional inputs. For example:

```
mutation updateRecord(input: UpdateRecordMutationInput!) {
  updatedRecord { ... }
}

input  UpdateRecordMutationInput {
  fieldA: Int
  fieldB: String!
}
```

Possible values for fieldA are blank, null or some integer. Blank corresponds to undefined in graphql-js, and is supported in graphql-java. Inputs are implemented as Maps in graphql-java, and whether a field is left blank can be checked by Map.containsKey(). One might interpret Blank as "don't update this field".

I suggest implementing some wrapper class around optional input fields.

**Comment by dkuc84** [comment]
In Java all objects are nullable by default which is also their default value. Kotlin requires variables/values to be initialized upon their declaration either from the user input OR by providing defaults (even if they are marked as nullable). 

Therefore in order for GraphQL input field to be optional it needs to be nullable and also specify default Kotlin value. So your example input could be implemented as

```kotlin
data class UpdateRecordMutation(val fieldA: Int? = null, val fieldB: String)
```

**Comment by dkuc84** [comment]
Updated example app: https://github.com/ExpediaDotCom/graphql-kotlin/pull/52

**Comment by dkuc84** [comment]
Also updated documentation: https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Arguments

**Comment by smyrick** [comment]
Unfortunately we can get the default values from Kotlin reflection right now either so the default values will not be exposed explicitly but you can always add it in the description of the argument with [`@GraphQLDescription`](https://github.com/ExpediaDotCom/graphql-kotlin/wiki/@GraphQLDescription)

**Comment by camuthig** [comment]
I know this ticket is old and closed, but my question is related to something the OP mentioned that I believe was not included in the original responses.

Do you have any thoughts on supporting some sort of `Optional` wrapper on the input field values to help create the ternary state defined in the GraphQL spec ("not provided", "provided as null", "provided with value")?

So the input class might look something like this

```kotlin
class MyInput(val requiredField: Int, val optionalField: Optional<Int?>)
```
I don't know that the Java `Optional` would be the best choice here, but something similar to it could be helpful, I think. If something like this is already possible, and I'm just not aware of it, let me know.

**Comment by smyrick** [comment]
@camuthig What is the `ternary state` you are referring to in the GraphQL spec?

From the spec: https://graphql.org/learn/schema/#arguments

> Arguments can be either required or optional. When an argument is optional, we can define a default value....


This means there is really only two states for arguments, required or not. In both Kotlin and GraphQL we represent this with nullability. So if an input is nullable, then it is optional.


```kotlin
fun helloWorld(name: String?) = if (name == null) "Hello world!" else "Hello $name!"
```

means I can query it in either way

```graphql
query NoName {
  helloWorld
}

query WithName {
  helloWorld(name: "Shane")
}
```

----------

As for Java 8 `Optional`, you don't need to use that in Kotlin code anymore since it Kotlin has null built into the typesystem, so you will always have to check null arguments `String?` vs `String`

**Comment by camuthig** [comment]
I think I was too ambiguous without realizing it, sorry. The specific functionality I am thinking of is the input coercion on input objects:

https://graphql.github.io/graphql-spec/June2018/#sec-Input-Objects (see: Input Coercion)

> * If no value is provided for a defined input object field and that field definition provides a default value, the default value should be used. If no default value is provided and the input object field’s type is non‐null, an error should be thrown. Otherwise, if the field is not required, then no entry is added to the coerced unordered map.
> * If the value null was provided for an input object field, and the field’s type is not a non‐null type, an entry in the coerced unordered map is given the value null. In other words, there is a semantic difference between the explicitly provided value null versus having not provided a value.

So something more along the lines of

```kotlin
// What I believe is currently possible. This will not differentiate between null and not present nickname
data class UpdateUserInput(val name: String, val nickname: String? = null)

fun updateUser(input: UpdateUserInput): User { }
```

```graphql
mutation WithNickname {
  updateUser(input: { name: "Christopher" , nickname: "Chris"}) {
    name
    nickname
  }
}

mutation WithoutNickname {
  updateUser(input: { name: "Christopher"}) {
    name
    nickname
  }
}

mutation RemoveNickname {
  updateUser(input: { name: "Christopher", nickname: null}) {
    name
    nickname
  }
}
```

**Comment by Togrias** [comment]
No longer using this library at this time, but my implementation for the above relies on a sealed class.
`MaybeDefined<T>`, with singleton object `Undefined` and sub-class `Defined<T>`, thus named to mimic graphql-js.

My suggestion was to have the above as wrappers within this library. So:
`fun editUser(name: MaybeDefined<String?>)` would generate a nullable `String` argument with the 3 possible states described.
