### ISSUE TITLE
Root Resolvers

### ISSUE THREAD

**Issue by bakert** [ExpediaDotCom/graphql-kotlin#74]
Apologies – I'm new to both GraphQL and Kotlin and this is more of a question than an issue, I think. But hopefully you can help me.

I issue a simple query something like this:

```
{
  bookById(id: 1) {
    name
    author {
      name
    }
  }
}
```

and get back the expected data. In my code that resolves this query I'm able to hook up `author` to a resolver (`DataFetcher`) by having a `var late init author` field on `Book` and by providing a `DataFetcher` that loads a Book (passed into `SchemaGeneratorConfig`'s constructor when generating the schema).

Is there any way to hook up the `bookByID` part of the query to also automatically look up what `DataFetcher` to use rather than having to provide a `fun bookById(id: Int): Book?`? I'd rather have all the resolution of a query work the same way. Is wanting that "wrong" for any reason?

https://www.graphql-java-kickstart.com/tools/schema-definition/ indicates that in java-graphql you can create a GraphQLQueryResolver which will be "searched for methods that map to fields in their respective root types". Is there some field or annotation that I can put on my root query class that would cause the same kind of searching for a GraphQLQueryResolver or something similar?

**Comment by smyrick** [comment]
@bakert The way we use reflection in `graphql-kotlin` requires that we look at the functions and parse the arguments and their types. However if you take a look at the `/example` directory, it has an file that uses Spring beans.

https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/example/src/main/kotlin/com.expedia.graphql.sample/query/NestedQueries.kt

This will delay running the resolver code unless the bean function is called/queried in GraphQL.

Does this answer your question?

**Comment by bakert** [comment]
Yes, thanks! The example is helpful.
