### ISSUE TITLE
Access to HttpServletRequest

### ISSUE THREAD

**Issue by JoniDS** [ExpediaDotCom/graphql-kotlin#75]
Is there any way to access/modify the **HttpServletRequest**, for example in a custom **GraphQLContext** ?

This would be particularly useful for i18n, so that we can read a **queryParam** and force a **messages** Locale (for Spring Boot)? 

Something like:
`RequestContextUtils.getLocaleResolver(request).setLocale(request, response, LocaleUtils.toLocale(request.getParam("lang")));`

Many thanks

**Comment by dkuc84** [comment]
Hello! Yes it is possible but it is actually actually outside of `graphql-kotlin` scope/responsibilities. What you are asking about can be achieved with `GraphQLContextBuilder` from [graphql-java-servlet](https://github.com/graphql-java-kickstart/graphql-java-servlet). Take a look at our [example app](https://github.com/ExpediaDotCom/graphql-kotlin/blob/master/example/src/main/kotlin/com.expedia.graphql.sample/context/MyGraphQLContextBuilder.kt) for example on how it could be used.

**Comment by JoniDS** [comment]
Unless I'm missing something, that's exactly what I did:

```
class MyGraphQLContext(
        val principal: Principal?,
        val httpServletRequest: HttpServletRequest? = null,
        handshakeRequest: HandshakeRequest? = null,
        subject: Subject? = null) : GraphQLContext(httpServletRequest, handshakeRequest, subject) {
    init {
        httpServletRequest?.let { request ->
            val newLocale = request.getParameter("lang")
            val localeResolver = RequestContextUtils.getLocaleResolver(request)
            RequestContextUtils.getLocaleResolver(request)?.setLocale(request, null, LocaleUtils.toLocale(newLocale))
        }
    }
}
```

But the response is not exposed, so I can change the locale for the response.

**Comment by JoniDS** [comment]
Got it,

I was using the old "com.graphql-java" groupId instead of "com.graphql-java-kickstart".
The old one was not exposing the response, but the new one is.
Apologies for taking your time.

Thank you
