### ISSUE TITLE
Don't include directive names automatically via GraphQLDescription?

### ISSUE THREAD

**Issue by d4rken** [ExpediaDotCom/graphql-kotlin#79]
https://github.com/ExpediaDotCom/graphql-kotlin/blob/861443970ae9859710967ae65c257e23bee47595/src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt#L23-L32

Currently we include directives names automatically in schema descriptions, I think this should not be done.

* Duplicate information: The graphQL fields already support `deprecated`, we don't need an additional `Directive: deprecated` in the description
* Exposing internal implementation details: Something like `@requiresPermision(...)` is not necessarily something that should be exposed

I think the option is good, but it should not be the default, AFAIK if desired, a developer could use `SchemaGeneratorHooks.onRewireGraphQLType` to achieve the same. We could provide a helper method that appends directive names to the description.

**Comment by dkuc84** [comment]
`deprecated` directive is a kind of an oddball directive as that is the only one that is exposed through introspection. We envisioned use cases where exposing this information would be beneficial to the clients, one example would be to mark some queries `experimental` (opposite of deprecated) so from a single service you would be able to easily differentiate between the two. That being said there are also many use cases when exposing this data might not be desirable.

Currently we print out all the applicable directive names (it is just a comment) but I agree that this should be configurable. Ideally we should have some mechanism to limit the exposure of those directives. We'll look into this and get back to you.

See corresponding discussion around: https://github.com/facebook/graphql/issues/300 and https://github.com/graphql-java/graphql-java/issues/1017

**Comment by d4rken** [comment]
Hm, I see. Theoretically this could also be done by adding an `expose: Boolean = false` to `GraphQLDirective`, though im not sure how we would best put the information into the schema then, for users of those pattern just the directive name would probably be not enough...

Seems the discussion on the spec in that regard is still on-going, I'd vote to remove this behavior until it is either in spec or someone presents an actual use-case for it.

**Comment by rickfast** [comment]
I agree with @d4rken on this - I'd rather just wait for schema directives to be added to introspection
