### ISSUE TITLE
How to ensure custom scalar is output in schema?

### ISSUE THREAD

**Issue by bakert** [ExpediaDotCom/graphql-kotlin#83]
I am using SchemaGeneratorHooks to provide a Url custom scalar (graphql.scalars.url.UrlScalar from graphql-java-extended-scalars).

Everything works great except `scalar Url` is not present in the schema as printed by SchemaPrinter.

How do I turn that on?

This is my SchemaGeneratorHooks:

```
class CustomSchemaGeneratorHooks : SchemaGeneratorHooks {
    val urlScalar = UrlScalar()

    override fun willGenerateGraphQLType(type: KType): GraphQLType? = when (type.classifier as? KClass<*>) {
        URL::class -> urlScalar
        else -> null
    }
}
```

And this is how I generate the schema:

```
    fun schema(): GraphQLSchema {
        val schemaConfig = SchemaGeneratorConfig(
            supportedPackages = listOf("com.cubetutor.api.graphql"),
            topLevelQueryName = "Query",
            topLevelMutationName = "Mutation",
            hooks = CustomSchemaGeneratorHooks(),
            dataFetcherFactory = ResolverFactory()
        )

        val schema = toSchema(
            queries = listOf(TopLevelObjectDef(CubeQuery())),
            mutations = emptyList<TopLevelObjectDef>(),
            config = schemaConfig
        )
        println(SchemaPrinter().print(schema)) // <-- this schema does not contain `scalar Url` and is therfore invalid
        return schema
    }
```

Thanks!

**Comment by d4rken** [comment]
You need to tell the schema generator how to convert your new type with a `Coercing` impementation:

https://github.com/ExpediaDotCom/graphql-kotlin/blob/f3c4c40f7c8926c61dd6d624ef8dcb6ad73c0a65/example/src/main/kotlin/com.expedia.graphql.sample/extension/CustomSchemaGeneratorHooks.kt#L37

**Comment by bakert** [comment]
That's theoretically covered by UrlScalar provided by https://github.com/graphql-java/graphql-java-extended-scalars/blob/master/src/main/java/graphql/scalars/url/UrlScalar.java – or possibly I am terminally confused :D

**Comment by bakert** [comment]
Thinking about this a bit more it's probably because UrlScalar isn't part of what gets inspected when forming the schema? I tried adding "graphql.scalars.url" to the list of supported packages in the SchemaGeneratorConfig but this did not help. Does the code need to be kotlin to be introspected correctly?

**Comment by d4rken** [comment]
Not sure, you could set a break point here and check what happens: 

https://github.com/ExpediaDotCom/graphql-kotlin/blob/f3c4c40f7c8926c61dd6d624ef8dcb6ad73c0a65/src/main/kotlin/com/expedia/graphql/schema/generator/SubTypeMapper.kt#L10-L13

**Comment by d4rken** [comment]
Nope, works for me as far as I see.

https://github.com/ExpediaDotCom/graphql-kotlin/compare/master...d4rken:pr-i83

```
someUrlScalar: Url!
```
![screenshot from 2018-12-03 15-11-48](https://user-images.githubusercontent.com/1439229/49378793-ccf45400-f70d-11e8-9d52-932412f9ecd6.png)
![screenshot from 2018-12-03 15-13-28](https://user-images.githubusercontent.com/1439229/49378868-02993d00-f70e-11e8-8f42-c3a018fad944.png)

**Comment by dkuc84** [comment]
Per @d4rken comment registration of custom scalars seems to be working fine. I believe your question is about behavior of `graphql.schema.idl.SchemaPrinter` which by default does not print out scalars.

Simply change it to
```SchemaPrinter(SchemaPrinter.Options.defaultOptions().includeScalarTypes(true)).print(schema)```

**Comment by bakert** [comment]
Oh man. You are right. I see it in /graphql/schema.json – sorry for my confusion! And thanks for the SchemaPrinter hint!
