### ISSUE TITLE
Support explicit order of directives

### ISSUE THREAD

**Issue by dkuc84** [ExpediaDotCom/graphql-kotlin#95]
Users can specify multiple directives on the target fields, e.g.

```kotlin
class MyQuery  {

  @Directive1
  @Directive2
  fun doSomething(): String {
    // does something
  }
}
```

Currently we process those directives in the order annotations are returned by Java/Kotlin. This order is implied but it is also unlikely the default behavior will change in the near future.

We should explore whether we would want to add explicit mechanism for ordering the directives. We could consider doing something similar to how Spring orders their annotations.

**Comment by d4rken** [comment]
In what way are they not ordered? AFAIK the annotations are arrays, or at least lists, and we process them as such. So the order in which they are processed should be either top-to-bottom or bottom-to-top?

We could add a unit-test though that checks this...

**Comment by dkuc84** [comment]
AFAIK neither [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-annotated-element/index.html) nor [Java](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/AnnotatedElement.html) explicitly specify the order in which annotations are read. This means that while it is true that currently the returned array is in the order that they are defined on the fields there is no guarantee that this might not change in the future.

**Comment by dkuc84** [comment]
I was thinking whether we should do something similar to what Spring does in their usage of `Ordered` (e.g. using Spring annotations ensuring that we run in transaction `@Transactional` only if data is not cached using `@Cacheable`, etc)

**Comment by d4rken** [comment]
I think java [does](https://stackoverflow.com/questions/28067074/java-annotations-reflection-ordering/30222541#30222541) guarantee ordering and thus Kotlin too.

Functionality wise I also thought about [Spring](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/annotation/Order.html), but I'm not sure we need new annotation for that. We could also add paramters to `GraphQLDirective`, e.g. `priority`.

Has this come up in a use-case? I'm not sure we should add this just because java/kotlin could change behavior, that's a bit Pandora's box.

**Comment by dkuc84** [comment]
I did saw that post but it also reiterates that while currently there is an order it is implied indirectly and there is no guarantee it might not change in the future. That being said I've updated the original description to reflect it is exploratory.

**Comment by smyrick** [comment]
I am also fine not doing anything until we need to. And if we do implement maybe just adding a simple `priority: Int`

**Comment by dkuc84** [comment]
Closing this as I don't think we'll be doing this anytime soon. We'll reopen if the need arise.
